version: '3'

services:
  coordinator:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_TYPE=coordinator
    ports:
      - "5432:5432"

  worker1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_TYPE=worker
    ports:
      - "5433:5432"  # Map host port 5433 to container port 5432 for worker1

  worker2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_TYPE=worker
    ports:
      - "5434:5432"  # Map host port 5434 to container port 5432 for worker2
